"""empty message

Revision ID: 13934a1ca6b4
Revises: 1eb09f605ac7
Create Date: 2024-08-08 12:40:52.872112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13934a1ca6b4'
down_revision = '1eb09f605ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_desc', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('short_desc')

    # ### end Alembic commands ###
